# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestprofilePicture():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testprofilePicture(self):
    self.driver.get("http://localhost:5173/login")
    self.driver.set_window_size(1550, 830)
    self.driver.find_element(By.ID, ":r0:").click()
    self.driver.find_element(By.ID, ":r0:").send_keys("faraz@gmail.com")
    self.driver.find_element(By.ID, ":r1:").click()
    self.driver.find_element(By.ID, ":r1:").send_keys("123456Q@")
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root").click()
    self.driver.find_element(By.CSS_SELECTOR, ".css-1mwacqe").click()
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-textInherit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".css-u672sz-MuiAvatar-root").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").send_keys("C:\\Users\\maazb\\OneDrive\\Desktop\\big-chungus.webp")
    self.driver.find_element(By.CSS_SELECTOR, ".css-u672sz-MuiAvatar-root").click()
  
